const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#8B2BE2",
    background: "#F5F0FF",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#8B2BE2",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE0FF",
    secondaryForeground: "#4A0E80",
    muted: "#EDE0FF",
    mutedForeground: "#6B4A99",
    accent: "#E23B2B",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#D6B8FF",
    input: "#EDE0FF",
    berry: "#8B2BE2",
    berryLight: "#B06AFF",
    berryDark: "#5A0EAD",
    red: "#E23B2B",
    green: "#22C55E",
  },
  dark: {
    text: "#F5F0FF",
    tint: "#B06AFF",
    background: "#0D0A1A",
    foreground: "#F5F0FF",
    card: "#1A1030",
    cardForeground: "#F5F0FF",
    primary: "#B06AFF",
    primaryForeground: "#0D0A1A",
    secondary: "#241640",
    secondaryForeground: "#D6B8FF",
    muted: "#241640",
    mutedForeground: "#9B7CC4",
    accent: "#FF5A4A",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#3A2660",
    input: "#241640",
    berry: "#B06AFF",
    berryLight: "#CFA0FF",
    berryDark: "#8B2BE2",
    red: "#FF5A4A",
    green: "#4ADE80",
  },
  radius: 12,
};

export default colors;
